openapi: '3.0.3'
info:
  title: ライフゲームサーバ
  version: '1.0'
servers:
  - url: https://localhost/v1
paths:
  /next:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Board'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Board'
components:
  schemas:
    Board:
      type: object
      properties:
        cells:
          type: array
          items:
            type: array
            items:
              type: integer
      required:
        - cells
      example:
        cells:
          - [0, 1, 0]
          - [1, 1, 1]
          - [0, 1, 0]
